CREATE TABLE public.ciudadanos (
    id_ciudadano integer NOT NULL,
    comunidad integer,
    domicilio integer,
    jefe integer,
    cedula character(10) NOT NULL,
    nombres character varying(25) NOT NULL,
    apellidos character varying(25) NOT NULL,
    genero public.genero_persona NOT NULL,
    fecha_nacimiento date NOT NULL,
    telefono character(10) NOT NULL,
    correo character varying(40) NOT NULL,
    discapacidad character varying(255),
    enfermedad character varying(255),
    usuario character varying(25),
    contrasena character varying(255),
    estado public.tipo_cuenta,
    fecha date,
    hora time without time zone,
    eliminado boolean DEFAULT false NOT NULL,
    imagen text,
    provincia character varying(50),
    canton character varying(50)
);